-- SCRIPT DE REESTRUTURAÇÃO TOTAL SUPABASE - SISTEMA ÊXODO
-- Este script adiciona todas as colunas necessárias para garantir a sincronização completa.

-- === 1. TABELA CLIENTES ===
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS nome TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS nome_fantasia TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS tipo_pessoa TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cpf_cnpj TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS rg_ie TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS telefone TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS logradouro TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS numero TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS complemento TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS bairro TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cidade TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS estado TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cep TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS ponto_referencia TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS observacoes TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_nascimento TIMESTAMP WITH TIME ZONE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS profissao TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS foto_path TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS dados_extras JSONB;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS pets JSONB DEFAULT '[]'::jsonb;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS enderecos JSONB DEFAULT '[]'::jsonb;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS limite_credito NUMERIC DEFAULT 0;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS saldo_devedor NUMERIC DEFAULT 0;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS bloqueado BOOLEAN DEFAULT FALSE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS motivo_bloqueio TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS senha TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS email_login TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS habilita_taxi_dog BOOLEAN DEFAULT FALSE;

-- === 2. TABELA PRODUTOS ===
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS codigo TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS codigo_barras TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS nome TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS descricao TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS unidade TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS grupo TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS preco NUMERIC;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS preco_custo NUMERIC;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS estoque INTEGER DEFAULT 0;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS estoque_minimo INTEGER DEFAULT 0;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS ncm TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS cest TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS para_cozinha BOOLEAN DEFAULT FALSE;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS para_bar BOOLEAN DEFAULT FALSE;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS exibir_na_loja BOOLEAN DEFAULT FALSE;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS em_destaque BOOLEAN DEFAULT FALSE;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS fotos_urls JSONB DEFAULT '[]'::jsonb;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS foto_principal_url TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS descricao_ecommerce TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS peso_gramas INTEGER;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS altura_cm NUMERIC;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS largura_cm NUMERIC;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS profundidade_cm NUMERIC;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]'::jsonb;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS variacoes JSONB DEFAULT '[]'::jsonb;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS tem_variacoes BOOLEAN DEFAULT FALSE;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS adicionais JSONB DEFAULT '[]'::jsonb;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS tem_adicionais BOOLEAN DEFAULT FALSE;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS observacao_padrao TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS fornecedor_id TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS fornecedor_nome TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS estoque_por_fornecedor JSONB DEFAULT '{}'::jsonb;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS pedido_compra_gerado BOOLEAN DEFAULT FALSE;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS data_ultimo_pedido TIMESTAMP WITH TIME ZONE;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS preco_promocional NUMERIC;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS promocao_inicio TIMESTAMP WITH TIME ZONE;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS promocao_fim TIMESTAMP WITH TIME ZONE;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS codigos_fornecedor JSONB DEFAULT '[]'::jsonb;

-- === 3. TABELA PEDIDOS ===
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS numero TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS cliente_id TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS cliente_nome TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS cliente_telefone TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS cliente_endereco TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS cliente_cpf_cnpj TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS vendedor_id TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS vendedor_nome TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS link_vendedor_id TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS link_vendedor_codigo TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS origem_ecommerce BOOLEAN DEFAULT FALSE;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS origem TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS data_pedido TIMESTAMP WITH TIME ZONE;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pendente';
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS total NUMERIC DEFAULT 0;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS observacoes TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS produtos JSONB DEFAULT '[]'::jsonb;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS servicos JSONB DEFAULT '[]'::jsonb;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS pagamentos JSONB DEFAULT '[]'::jsonb;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS materiais_consumidos JSONB DEFAULT '[]'::jsonb;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS delivery_info JSONB;

-- === 4. TABELA VENDAS BALCÃO ===
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS numero TEXT;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS data_venda TIMESTAMP WITH TIME ZONE;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS cliente_id TEXT;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS cliente_nome TEXT;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS cliente_telefone TEXT;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS cliente_cpf_cnpj TEXT;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS itens JSONB DEFAULT '[]'::jsonb;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS tipo_pagamento TEXT;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS valor_total NUMERIC DEFAULT 0;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS valor_recebido NUMERIC;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS troco NUMERIC;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS operador TEXT;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS origem TEXT;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS observacoes TEXT;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS cancelado BOOLEAN DEFAULT FALSE;
ALTER TABLE vendas_balcao ADD COLUMN IF NOT EXISTS delivery_info JSONB;

-- === 5. TABELA ENTREGAS ===
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS "pedidoId" TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS "pedidoNumero" TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS "clienteNome" TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS "clienteTelefone" TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS logradouro TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS numero TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS bairro TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS cidade TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS estado TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS cep TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS complemento TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS "pontoReferencia" TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS "valorFrete" NUMERIC;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS "previsaoEntrega" TIMESTAMP WITH TIME ZONE;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS "dataEntrega" TIMESTAMP WITH TIME ZONE;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS "assinaturaRecebedor" TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE entregas ADD COLUMN IF NOT EXISTS observacoes TEXT;

-- === 6. TABELAS DE CAIXA ===
ALTER TABLE aberturas_caixa ADD COLUMN IF NOT EXISTS numero TEXT;
ALTER TABLE aberturas_caixa ADD COLUMN IF NOT EXISTS "dataAbertura" TIMESTAMP WITH TIME ZONE;
ALTER TABLE aberturas_caixa ADD COLUMN IF NOT EXISTS "valorInicial" NUMERIC;
ALTER TABLE aberturas_caixa ADD COLUMN IF NOT EXISTS observacao TEXT;
ALTER TABLE aberturas_caixa ADD COLUMN IF NOT EXISTS responsavel TEXT;
ALTER TABLE aberturas_caixa ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE aberturas_caixa ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE;

ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS "aberturaCaixaId" TEXT;
ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS "dataFechamento" TIMESTAMP WITH TIME ZONE;
ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS "valorEsperado" NUMERIC;
ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS "valorReal" NUMERIC;
ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS diferenca NUMERIC;
ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS sangrias JSONB DEFAULT '[]'::jsonb;
ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS suprimentos JSONB DEFAULT '[]'::jsonb;
ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS observacao TEXT;
ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS responsavel TEXT;
ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE fechamentos_caixa ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE;

-- === 7. TABELA FUNCIONÁRIOS ===
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS nome TEXT;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS telefone TEXT;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS senha TEXT;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS observacoes TEXT;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT TRUE;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS "temAcesso" BOOLEAN DEFAULT FALSE;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS "porcentagemComissao" NUMERIC DEFAULT 0;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS "tipoComissao" TEXT DEFAULT 'Porcentagem';
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS "valorComissao" NUMERIC DEFAULT 0;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE;
